package inventario;


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;




/**
 *
 * @author pablo
 */
public class GUIInventario extends javax.swing.JFrame {
    private TableRowSorter transcribirFiltro;
    String filtro;
    
    DefaultTableModel modelo;
    
    int filas;
 
   
    public GUIInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Cantidad En Stock");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Categoria");
        modelo.addColumn("Cantidad Recompra");
        GUIInventario.tabla.setModel(modelo);
    }
    
    public void AgregarTabla(){
         String codigo = cCodigo.getText();
         String nombre = cNombre.getText();
         
         String cantidadText = cCantidadStock.getText();
         int cantidad = cantidadText.isEmpty() ? 0 : Integer.parseInt(cantidadText);
         
         String precioText = cPrecio.getText();
         double precio = precioText.isEmpty() ? 0.0 : Double.parseDouble(precioText);
         
         String categoria = cCategoria.getText();
         
         String cantidadRecompraText = cCantidadR.getText();
         int cantidadRe = cantidadRecompraText.isEmpty() ? 0 : Integer.parseInt(cantidadRecompraText);
         
         this.validarCodigosIngresados();
         
         if(codigo.isEmpty() || nombre.isEmpty() ||  cantidad<=0 || precio<=0 || categoria.isEmpty() || cantidadRe<=0){
             
             JOptionPane.showMessageDialog(null, "Deje llenar los campos");
             }else{
        
            String []info  = new String[6];
            info[0] = cCodigo.getText();
            info[1] = cNombre.getText();
            info[2] = cCantidadStock.getText();
            info[3] = cPrecio.getText();
            info[4] = cCategoria.getText();
            info[5] = cCantidadR.getText();
            modelo.addRow(info);
 
             cCodigo.setText("");
             cNombre.setText("");
             cCantidadStock.setText("");
             cPrecio.setText("");
             cCategoria.setText("");
             cCantidadR.setText("");
         }
    }
    public void validarCodigosIngresados(){
        for(int i=0; i<tabla.getRowCount();i++){
            if(tabla.getValueAt(i, 0).equals(cCodigo.getText())){
                JOptionPane.showMessageDialog(null, "Error, El Codigo Ya Existe");
                modelo.removeRow(i);
        }else{
                AgregarTabla();
            }
    }}
    
    
    

    

         
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cPrecio = new javax.swing.JTextField();
        cCantidadStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cCantidadR = new javax.swing.JTextField();
        cNombre = new javax.swing.JTextField();
        cCodigo = new javax.swing.JTextField();
        cEliminar = new javax.swing.JButton();
        cAgregar = new javax.swing.JButton();
        cModificar = new javax.swing.JButton();
        cCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        cNom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cantidad En Stock");

        jLabel4.setText("Precio Unitario");

        jLabel5.setText("Categoria");

        cPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPrecioKeyTyped(evt);
            }
        });

        cCantidadStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cCantidadStockKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad recompra");

        cCantidadR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cCantidadRKeyTyped(evt);
            }
        });

        cEliminar.setText("Eliminar");
        cEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEliminarActionPerformed(evt);
            }
        });

        cAgregar.setText("Agregar");
        cAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAgregarActionPerformed(evt);
            }
        });

        cModificar.setText("Modificar");
        cModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cModificarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad En Stock", "Precio  Unitario", "Categoria", "Cantidad Recompra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jButton3.setText("Buscar Por Nombre");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNomKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar Por Codigo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cCodKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(cCategoria)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cCantidadR))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cCantidadStock)
                                .addComponent(cNombre)
                                .addComponent(cCodigo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cModificar)
                        .addGap(18, 18, 18)
                        .addComponent(cEliminar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cNom)
                            .addComponent(cCod, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cCantidadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cModificar)
                        .addComponent(cEliminar)
                        .addComponent(cAgregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(cNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEliminarActionPerformed
        modelo.removeRow(tabla.getSelectedRow());
         cCodigo.setText("");
             cNombre.setText("");
             cCantidadStock.setText("");
             cPrecio.setText("");
             cCategoria.setText("");
             cCantidadR.setText("");
    }//GEN-LAST:event_cEliminarActionPerformed

    private void cAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAgregarActionPerformed
           this.AgregarTabla();
         
    }//GEN-LAST:event_cAgregarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       int  seleccionarFila = tabla.getSelectedRow();
       if (seleccionarFila >= 0) {
                    cCodigo.setText((String) tabla.getValueAt(seleccionarFila, 0));
                    cNombre.setText((String) tabla.getValueAt(seleccionarFila, 1));
                    cCantidadStock.setText(tabla.getValueAt(seleccionarFila, 2).toString());
                    cPrecio.setText(tabla.getValueAt(seleccionarFila, 3).toString());
                    cCategoria.setText((String) tabla.getValueAt(seleccionarFila, 4));
                    cCantidadR.setText(tabla.getValueAt(seleccionarFila, 5).toString());
                    filas=seleccionarFila;
                }
       
    }//GEN-LAST:event_tablaMouseClicked

    private void cPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPrecioKeyTyped
        char caracter = evt.getKeyChar();
        
        if(caracter<'0'  ||  caracter>'9')  evt.consume();
    }//GEN-LAST:event_cPrecioKeyTyped

    private void cCantidadStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCantidadStockKeyTyped
        char caracter = evt.getKeyChar();
        
        if(caracter<'0'  ||  caracter>'9')  evt.consume();
    }//GEN-LAST:event_cCantidadStockKeyTyped

    private void cCantidadRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCantidadRKeyTyped
        char caracter = evt.getKeyChar();
        
        if(caracter<'0'  ||  caracter>'9')  evt.consume();
    }//GEN-LAST:event_cCantidadRKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cNom.addKeyListener(new  KeyAdapter(){

         public void  keyReleased(final KeyEvent e){
            String cadena  = cNom.getText();
            cNom.setText(cadena);
            repaint();

         filtro();
        }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNomKeyTyped
        transcribirFiltro = new TableRowSorter(tabla.getModel());
        tabla.setRowSorter(transcribirFiltro);
    }//GEN-LAST:event_cNomKeyTyped

    private void cCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCodKeyTyped
        transcribirFiltro = new TableRowSorter(tabla.getModel());
        tabla.setRowSorter(transcribirFiltro);
    }//GEN-LAST:event_cCodKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cCod.addKeyListener(new  KeyAdapter(){

         public void  keyReleased(final KeyEvent e){
            String cadena  = cCod.getText();
            cCod.setText(cadena);
            repaint();

         filtroCod();
        }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cModificarActionPerformed
             String []modificar  = new String[6];
            modificar[0] = cCodigo.getText();
            modificar[1] = cNombre.getText();
            modificar[2] = cCantidadStock.getText();
            modificar[3] = cPrecio.getText();
            modificar[4] = cCategoria.getText();
            modificar[5] = cCantidadR.getText();
            
             cCodigo.setText("");
             cNombre.setText("");
             cCantidadStock.setText("");
             cPrecio.setText("");
             cCategoria.setText("");
             cCantidadR.setText("");
            
            for(int i=0; i<tabla.getColumnCount();i++){
                modelo.setValueAt(modificar[i], filas, i);
            }
            
    }//GEN-LAST:event_cModificarActionPerformed

    public void filtro(){
        filtro  = cNom.getText();
        transcribirFiltro.setRowFilter(RowFilter.regexFilter(cNom.getText(), 1));
    }
    public void filtroCod(){
        filtro  = cCod.getText();
        transcribirFiltro.setRowFilter(RowFilter.regexFilter(cCod.getText(), 0));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cAgregar;
    private javax.swing.JTextField cCantidadR;
    private javax.swing.JTextField cCantidadStock;
    private javax.swing.JTextField cCategoria;
    private javax.swing.JTextField cCod;
    private javax.swing.JTextField cCodigo;
    private javax.swing.JButton cEliminar;
    private javax.swing.JButton cModificar;
    private javax.swing.JTextField cNom;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
